name: WeChat Daily Push

on:
  schedule:
    # 每天 UTC 时间 0:30 运行（北京时间 8:30）
    - cron: '30 0 * * *'
  workflow_dispatch: # 允许手动触发运行

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install requests # 安装脚本需要的库

      - name: Run WeChat Push Script
        env:
          # 将我们在Settings中配置的Secrets映射到环境变量
          APPID: ${{ secrets.APPID }}
          APPSECRET: ${{ secrets.APPSECRET }}
          OPENID_LIST: ${{ secrets.OPENID_LIST }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        run: python wechat_push.py

      - name: Notify on Failure
        if: failure() # 如果上面的步骤失败，则运行此步骤
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'WeChat Daily Push Failed',
              body: 'The scheduled WeChat push job failed! Please check the logs.'
            })